language: ruby

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.vst k.gemfile

rvm:
  - '1.9.3'
  - '2.0.0'
  - '2.1.10'
  - '2.2.5'
  - '2.3.1'

addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 743bf63d7a422064551b35931628682c6cad81a30743edee7ff9ea8af061397d

env:
  - BUILDER=travis

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
