language: ruby
cache: bundler
before_install: gem update bundler

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

rvm:
  - '2.3.3'

addons:
  postgresql: '9.4'
  code_climate:
    repo_token: 743bf63d7a422064551b35931628682c6cad81a30743edee7ff9ea8af061397d

env:
  - BUILDER=travis
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
